# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\qa\sg_envs\dev\tk\tk-framework-qtwidgets\python\note_input_widget\resources\note_input_widget.ui'
#
# Created: Thu Jul 04 10:32:11 2024
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_NoteInputWidget(object):
    def setupUi(self, NoteInputWidget):
        NoteInputWidget.setObjectName("NoteInputWidget")
        NoteInputWidget.resize(848, 502)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NoteInputWidget.sizePolicy().hasHeightForWidth())
        NoteInputWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_5 = QtGui.QVBoxLayout(NoteInputWidget)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stacked_widget = QtGui.QStackedWidget(NoteInputWidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.note_editor_page = QtGui.QWidget()
        self.note_editor_page.setObjectName("note_editor_page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.note_editor_page)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_entry = NoteEditor(self.note_editor_page)
        self.text_entry.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_entry.setObjectName("text_entry")
        self.verticalLayout.addWidget(self.text_entry)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.close = QtGui.QPushButton(self.note_editor_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setToolTip("")
        self.close.setObjectName("close")
        self.horizontalLayout_5.addWidget(self.close)
        self.submit = QtGui.QPushButton(self.note_editor_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit.sizePolicy().hasHeightForWidth())
        self.submit.setSizePolicy(sizePolicy)
        self.submit.setIconSize(QtCore.QSize(20, 20))
        self.submit.setObjectName("submit")
        self.horizontalLayout_5.addWidget(self.submit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.thumbnail = QtGui.QLabel(self.note_editor_page)
        self.thumbnail.setEnabled(True)
        self.thumbnail.setMinimumSize(QtCore.QSize(96, 75))
        self.thumbnail.setMaximumSize(QtCore.QSize(96, 75))
        self.thumbnail.setText("")
        self.thumbnail.setPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets/rect_512x400.png"))
        self.thumbnail.setScaledContents(True)
        self.thumbnail.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.thumbnail.setMargin(3)
        self.thumbnail.setObjectName("thumbnail")
        self.horizontalLayout.addWidget(self.thumbnail)
        self.button_layout_right = QtGui.QVBoxLayout()
        self.button_layout_right.setSpacing(3)
        self.button_layout_right.setContentsMargins(5, -1, -1, -1)
        self.button_layout_right.setObjectName("button_layout_right")
        self.attach = QtGui.QToolButton(self.note_editor_page)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.note_input_widget/paper_clip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attach.setIcon(icon)
        self.attach.setAutoRaise(True)
        self.attach.setObjectName("attach")
        self.button_layout_right.addWidget(self.attach)
        self.screenshot = QtGui.QToolButton(self.note_editor_page)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.note_input_widget/camera_hl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screenshot.setIcon(icon1)
        self.screenshot.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.screenshot.setAutoRaise(True)
        self.screenshot.setObjectName("screenshot")
        self.button_layout_right.addWidget(self.screenshot)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.button_layout_right.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.button_layout_right)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stacked_widget.addWidget(self.note_editor_page)
        self.preview_page = QtGui.QWidget()
        self.preview_page.setObjectName("preview_page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.preview_page)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.new_note_frame = QtGui.QFrame(self.preview_page)
        self.new_note_frame.setStyleSheet("")
        self.new_note_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.new_note_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.new_note_frame.setObjectName("new_note_frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.new_note_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.new_note_placeholder = QtGui.QLabel(self.new_note_frame)
        self.new_note_placeholder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.new_note_placeholder.setObjectName("new_note_placeholder")
        self.verticalLayout_4.addWidget(self.new_note_placeholder)
        self.verticalLayout_3.addWidget(self.new_note_frame)
        self.stacked_widget.addWidget(self.preview_page)
        self.attachments_page = QtGui.QWidget()
        self.attachments_page.setObjectName("attachments_page")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.attachments_page)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.attachment_list = QtGui.QWidget(self.attachments_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attachment_list.sizePolicy().hasHeightForWidth())
        self.attachment_list.setSizePolicy(sizePolicy)
        self.attachment_list.setObjectName("attachment_list")
        self.attachments_list_layout = QtGui.QVBoxLayout(self.attachment_list)
        self.attachments_list_layout.setSpacing(0)
        self.attachments_list_layout.setContentsMargins(0, 0, 0, 0)
        self.attachments_list_layout.setObjectName("attachments_list_layout")
        self.attachment_list_tree = QtGui.QTreeWidget(self.attachment_list)
        self.attachment_list_tree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.attachment_list_tree.setRootIsDecorated(False)
        self.attachment_list_tree.setItemsExpandable(False)
        self.attachment_list_tree.setHeaderHidden(True)
        self.attachment_list_tree.setExpandsOnDoubleClick(False)
        self.attachment_list_tree.setObjectName("attachment_list_tree")
        self.attachment_list_tree.headerItem().setText(0, "1")
        self.attachments_list_layout.addWidget(self.attachment_list_tree)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_button = QtGui.QToolButton(self.attachment_list)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.note_input_widget/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon2)
        self.add_button.setAutoRaise(True)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_4.addWidget(self.add_button)
        self.remove_button = QtGui.QToolButton(self.attachment_list)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.note_input_widget/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_button.setIcon(icon3)
        self.remove_button.setAutoRaise(True)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_4.addWidget(self.remove_button)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.close_attachments = QtGui.QPushButton(self.attachment_list)
        self.close_attachments.setObjectName("close_attachments")
        self.horizontalLayout_4.addWidget(self.close_attachments)
        self.add_attachments = QtGui.QPushButton(self.attachment_list)
        self.add_attachments.setObjectName("add_attachments")
        self.horizontalLayout_4.addWidget(self.add_attachments)
        self.attachments_list_layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.attachment_list)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.stacked_widget.addWidget(self.attachments_page)
        self.verticalLayout_5.addWidget(self.stacked_widget)

        self.retranslateUi(NoteInputWidget)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NoteInputWidget)

    def retranslateUi(self, NoteInputWidget):
        NoteInputWidget.setWindowTitle(QtGui.QApplication.translate("NoteInputWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.text_entry.setPlaceholderText(QtGui.QApplication.translate("NoteInputWidget", "You can add people by referring to them by @name", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setText(QtGui.QApplication.translate("NoteInputWidget", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.submit.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Create a new note", None, QtGui.QApplication.UnicodeUTF8))
        self.submit.setText(QtGui.QApplication.translate("NoteInputWidget", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.attach.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Attach Files", None, QtGui.QApplication.UnicodeUTF8))
        self.attach.setText(QtGui.QApplication.translate("NoteInputWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.screenshot.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Take a screenshot", None, QtGui.QApplication.UnicodeUTF8))
        self.screenshot.setText(QtGui.QApplication.translate("NoteInputWidget", "Attach Screenshot", None, QtGui.QApplication.UnicodeUTF8))
        self.new_note_placeholder.setText(QtGui.QApplication.translate("NoteInputWidget", "Click to create a new note...", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Add another attachment to the list. Click \"Attach\" to add the attachments to the note.", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button.setAccessibleName(QtGui.QApplication.translate("NoteInputWidget", "add_button", None, QtGui.QApplication.UnicodeUTF8))
        self.add_button.setText(QtGui.QApplication.translate("NoteInputWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_button.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Remove the selected attachment from the list.", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_button.setAccessibleName(QtGui.QApplication.translate("NoteInputWidget", "remove_button", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_button.setText(QtGui.QApplication.translate("NoteInputWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.close_attachments.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Cancel adding the attachments to the note", None, QtGui.QApplication.UnicodeUTF8))
        self.close_attachments.setText(QtGui.QApplication.translate("NoteInputWidget", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.add_attachments.setToolTip(QtGui.QApplication.translate("NoteInputWidget", "Attach files to the note. Attachments will be created when the note is submitted.", None, QtGui.QApplication.UnicodeUTF8))
        self.add_attachments.setText(QtGui.QApplication.translate("NoteInputWidget", "Attach All", None, QtGui.QApplication.UnicodeUTF8))

from ..note_editor import NoteEditor
from . import resources_rc
