# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'context_editor_widget.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_ContextWidget(object):
    def setupUi(self, ContextWidget):
        ContextWidget.setObjectName("ContextWidget")
        ContextWidget.resize(285, 89)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ContextWidget.sizePolicy().hasHeightForWidth())
        ContextWidget.setSizePolicy(sizePolicy)
        ContextWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout_2 = QtGui.QVBoxLayout(ContextWidget)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(ContextWidget)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edit_widget = QtGui.QWidget(ContextWidget)
        self.edit_widget.setObjectName("edit_widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.edit_widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.task_label = QtGui.QLabel(self.edit_widget)
        self.task_label.setMinimumSize(QtCore.QSize(0, 0))
        self.task_label.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_label.setToolTip("")
        self.task_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.task_label.setOpenExternalLinks(True)
        self.task_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.task_label.setObjectName("task_label")
        self.gridLayout.addWidget(self.task_label, 0, 0, 1, 1)
        self.task_widgets_layout = QtGui.QHBoxLayout()
        self.task_widgets_layout.setSpacing(4)
        self.task_widgets_layout.setContentsMargins(-1, -1, -1, 1)
        self.task_widgets_layout.setObjectName("task_widgets_layout")
        self.task_display = QtGui.QLabel(self.edit_widget)
        self.task_display.setMinimumSize(QtCore.QSize(0, 0))
        self.task_display.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_display.setMargin(4)
        self.task_display.setOpenExternalLinks(True)
        self.task_display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.task_display.setObjectName("task_display")
        self.task_widgets_layout.addWidget(self.task_display)
        self.task_search_layout = QtGui.QHBoxLayout()
        self.task_search_layout.setSpacing(0)
        self.task_search_layout.setObjectName("task_search_layout")
        self.task_search = GlobalSearchWidget(self.edit_widget)
        self.task_search.setMinimumSize(QtCore.QSize(0, 32))
        self.task_search.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_search.setObjectName("task_search")
        self.task_search_layout.addWidget(self.task_search)
        self.task_menu_btn = QtGui.QToolButton(self.edit_widget)
        self.task_menu_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.task_menu_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.task_menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.context_selector/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_menu_btn.setIcon(icon)
        self.task_menu_btn.setIconSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setCheckable(False)
        self.task_menu_btn.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.task_menu_btn.setObjectName("task_menu_btn")
        self.task_search_layout.addWidget(self.task_menu_btn)
        self.task_search_layout.setStretch(0, 100)
        self.task_search_layout.setStretch(1, 1)
        self.task_widgets_layout.addLayout(self.task_search_layout)
        self.task_search_btn = QtGui.QToolButton(self.edit_widget)
        self.task_search_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.task_search_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.task_search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tk_framework_qtwidgets.context_selector/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_search_btn.setIcon(icon1)
        self.task_search_btn.setIconSize(QtCore.QSize(32, 32))
        self.task_search_btn.setCheckable(True)
        self.task_search_btn.setObjectName("task_search_btn")
        self.task_widgets_layout.addWidget(self.task_search_btn)
        self.task_widgets_layout.setStretch(0, 1)
        self.task_widgets_layout.setStretch(1, 100)
        self.task_widgets_layout.setStretch(2, 1)
        self.gridLayout.addLayout(self.task_widgets_layout, 0, 1, 1, 1)
        self.link_label = QtGui.QLabel(self.edit_widget)
        self.link_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.link_label.setOpenExternalLinks(True)
        self.link_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.link_label.setObjectName("link_label")
        self.gridLayout.addWidget(self.link_label, 1, 0, 1, 1)
        self.link_widgets_layout = QtGui.QHBoxLayout()
        self.link_widgets_layout.setSpacing(4)
        self.link_widgets_layout.setContentsMargins(-1, 1, -1, -1)
        self.link_widgets_layout.setObjectName("link_widgets_layout")
        self.link_display = QtGui.QLabel(self.edit_widget)
        self.link_display.setMinimumSize(QtCore.QSize(0, 0))
        self.link_display.setMaximumSize(QtCore.QSize(16777215, 32))
        self.link_display.setMargin(4)
        self.link_display.setOpenExternalLinks(True)
        self.link_display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.link_display.setObjectName("link_display")
        self.link_widgets_layout.addWidget(self.link_display)
        self.link_search = GlobalSearchWidget(self.edit_widget)
        self.link_search.setMinimumSize(QtCore.QSize(0, 32))
        self.link_search.setMaximumSize(QtCore.QSize(16777215, 32))
        self.link_search.setObjectName("link_search")
        self.link_widgets_layout.addWidget(self.link_search)
        self.link_search_btn = QtGui.QToolButton(self.edit_widget)
        self.link_search_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.link_search_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.link_search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.link_search_btn.setIcon(icon1)
        self.link_search_btn.setIconSize(QtCore.QSize(32, 32))
        self.link_search_btn.setCheckable(True)
        self.link_search_btn.setObjectName("link_search_btn")
        self.link_widgets_layout.addWidget(self.link_search_btn)
        self.link_widgets_layout.setStretch(0, 1)
        self.link_widgets_layout.setStretch(1, 100)
        self.link_widgets_layout.setStretch(2, 1)
        self.gridLayout.addLayout(self.link_widgets_layout, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 100)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.edit_widget)

        self.retranslateUi(ContextWidget)
        QtCore.QMetaObject.connectSlotsByName(ContextWidget)

    def retranslateUi(self, ContextWidget):
        ContextWidget.setWindowTitle(QtGui.QApplication.translate("ContextWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ContextWidget", "Task and Entity Link to apply to the selected item:", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setText(QtGui.QApplication.translate("ContextWidget", "Task: ", None, QtGui.QApplication.UnicodeUTF8))
        self.task_display.setText(QtGui.QApplication.translate("ContextWidget", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.task_search_btn.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Toggle this button to allow searching for a Task to associate with the selected item.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_search_btn.setText(QtGui.QApplication.translate("ContextWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.link_label.setText(QtGui.QApplication.translate("ContextWidget", "Link: ", None, QtGui.QApplication.UnicodeUTF8))
        self.link_display.setText(QtGui.QApplication.translate("ContextWidget", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.link_search_btn.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Toggle this button to allow searching for an entity to link to the selected item.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.link_search_btn.setText(QtGui.QApplication.translate("ContextWidget", "...", None, QtGui.QApplication.UnicodeUTF8))

from ..qtwidgets import GlobalSearchWidget
from . import resources_rc
